version: "3"
services:
  app:
    build:
      context: .
    volumes:
      - .:/core
    ports:
      - 80:80
    image: app:react
    container_name: react_container
    command: serve -s build -l 80
